.PHONY: clean All

All:
	@echo "----------Building project:[ first_programme - Debug ]----------"
	@cd "first_programme" && "$(MAKE)" -f  "first_programme.mk"
clean:
	@echo "----------Cleaning project:[ first_programme - Debug ]----------"
	@cd "first_programme" && "$(MAKE)" -f  "first_programme.mk" clean
