.PHONY: clean All

All:
	@echo "----------Building project:[ arrays - Debug ]----------"
	@cd "arrays" && "$(MAKE)" -f  "arrays.mk"
clean:
	@echo "----------Cleaning project:[ arrays - Debug ]----------"
	@cd "arrays" && "$(MAKE)" -f  "arrays.mk" clean
