.PHONY: clean All

All:
	@echo "----------Building project:[ first_workspace - Debug ]----------"
	@cd "first_workspace" && "$(MAKE)" -f  "first_workspace.mk"
clean:
	@echo "----------Cleaning project:[ first_workspace - Debug ]----------"
	@cd "first_workspace" && "$(MAKE)" -f  "first_workspace.mk" clean
